name: Deploy static content to Pages
on:
  push:
    branches: ["NEVER_USE_SYNC_YML_INSTEAD"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo disabled
